import type {
  CollectionId,
  GridLink,
  ItemId,
  NonEmptyText,
  RenderableCollection,
  SafeLocalLink,
  SectionId
} from "../collection/types";
import { createRenderError, type GridgenError, GridgenErrorCode } from "../errors/errors";
import { err, ok, type Result } from "../result/result";

const generatedFileComment = "<!-- Generated by gridgen. Do not edit by hand. -->";
const stylesheetUrlPrefix = "{{ '";
const stylesheetUrlSuffix = "' | relative_url }}";

/**
 * Static grid presentation layout.
 */
export type GridRenderLayout = "classic" | "poster";

/**
 * Liquid-safe local asset URL expression used in generated HTML.
 *
 * @property value Liquid expression string.
 */
export interface JekyllAssetUrlExpression {
  readonly value: string;
}

/**
 * Prepared image reference ready for HTML rendering.
 *
 * @property alt Resolved alt text.
 * @property src Generated local image source.
 */
export interface RenderGridImage {
  readonly alt: string;
  readonly src: JekyllAssetUrlExpression;
}

/**
 * Prepared recommendation item ready for HTML rendering.
 *
 * @property description Optional non-empty description.
 * @property id Stable item ID.
 * @property image Optional prepared generated image.
 * @property link Optional renderable item link.
 * @property title Optional non-empty title.
 */
export interface RenderGridItem {
  readonly description?: NonEmptyText;
  readonly id: ItemId;
  readonly image?: RenderGridImage;
  readonly link?: GridLink;
  readonly title?: NonEmptyText;
}

/**
 * Prepared recommendation section ready for HTML rendering.
 *
 * @property id Stable section ID.
 * @property items Ordered prepared items.
 * @property name Non-empty section title.
 */
export interface RenderGridSection {
  readonly id: SectionId;
  readonly items: readonly RenderGridItem[];
  readonly name: NonEmptyText;
}

/**
 * Prepared render input with all asset URLs already resolved.
 *
 * @property collectionId Stable collection ID.
 * @property layout Static presentation layout.
 * @property sections Ordered prepared sections.
 * @property stylesheetHref Shared stylesheet liquid expression.
 * @property title Non-empty collection title.
 */
export interface RenderGridInput {
  readonly collectionId: CollectionId;
  readonly layout: GridRenderLayout;
  readonly sections: readonly RenderGridSection[];
  readonly stylesheetHref: JekyllAssetUrlExpression;
  readonly title: NonEmptyText;
}

/**
 * Generated render-data image payload.
 *
 * @property alt Resolved alt text.
 * @property src Public image source URL.
 */
export interface RenderedGridImageJson {
  readonly alt: string;
  readonly src: string;
}

/**
 * Generated render-data item payload.
 *
 * @property description Optional item description.
 * @property id Stable item ID.
 * @property image Optional generated image payload.
 * @property link Optional renderable link href.
 * @property title Optional item title.
 */
export interface RenderedGridItemJson {
  readonly description?: string;
  readonly id: string;
  readonly image?: RenderedGridImageJson;
  readonly link?: string;
  readonly title?: string;
}

/**
 * Generated render-data section payload.
 *
 * @property id Stable section ID.
 * @property items Ordered item payloads.
 * @property name Section name.
 */
export interface RenderedGridSectionJson {
  readonly id: string;
  readonly items: readonly RenderedGridItemJson[];
  readonly name: string;
}

/**
 * Generated render-data collection payload consumed by generated React output.
 *
 * @property id Stable collection ID.
 * @property layout Static presentation layout.
 * @property renderDataVersion Generated render-data schema version.
 * @property sections Ordered section payloads.
 * @property title Collection title.
 */
export interface RenderedGridCollectionJson {
  readonly id: string;
  readonly layout: GridRenderLayout;
  readonly renderDataVersion: 1;
  readonly sections: readonly RenderedGridSectionJson[];
  readonly title: string;
}

/**
 * Prepared item image mapping used to build renderer input.
 *
 * @property itemId Stable item ID.
 * @property src Generated local image URL expression.
 */
export interface PreparedRenderImage {
  readonly itemId: ItemId;
  readonly src: JekyllAssetUrlExpression;
}

/**
 * Input used to prepare a render-ready collection from a renderable collection.
 *
 * @property collection Renderable source collection.
 * @property images Generated image URLs keyed by item ID.
 * @property layout Optional static presentation layout.
 * @property stylesheetHref Shared stylesheet liquid expression.
 */
export interface PrepareRenderGridInput {
  readonly collection: RenderableCollection;
  readonly images: readonly PreparedRenderImage[];
  readonly layout?: GridRenderLayout;
  readonly stylesheetHref: JekyllAssetUrlExpression;
}

type RenderableSectionInput = RenderableCollection["sections"][number];
type RenderableItemInput = RenderableSectionInput["items"][number];

/**
 * Converts a safe root-relative asset path into a Jekyll `relative_url` expression.
 *
 * @param href Safe local asset path.
 * @returns Liquid expression string for generated HTML attributes.
 */
export function createJekyllAssetUrlExpression(href: SafeLocalLink): JekyllAssetUrlExpression {
  return {
    value: `${stylesheetUrlPrefix}${href.value}${stylesheetUrlSuffix}`
  };
}

/**
 * Prepares one renderable collection for the HTML renderer.
 *
 * @param input Render preparation input.
 * @returns Prepared render model or a structured failure when an item image URL is missing.
 */
export function prepareRenderGrid(
  input: PrepareRenderGridInput
): Result<RenderGridInput, GridgenError> {
  const imageMap = createPreparedImageMap(input.images);

  if (!imageMap.ok) {
    return imageMap;
  }

  const sections = prepareRenderSections(input.collection.sections, imageMap.value);

  if (!sections.ok) {
    return sections;
  }

  return ok({
    collectionId: input.collection.id,
    layout: input.layout ?? "classic",
    sections: sections.value,
    stylesheetHref: input.stylesheetHref,
    title: input.collection.title
  });
}

function createPreparedImageMap(
  images: readonly PreparedRenderImage[]
): Result<ReadonlyMap<string, JekyllAssetUrlExpression>, GridgenError> {
  const imageMap = new Map<string, JekyllAssetUrlExpression>();

  for (const image of images) {
    if (imageMap.has(image.itemId.value)) {
      return err(
        createRenderError(GridgenErrorCode.RenderNotRenderable, "Duplicate generated image URL.", {
          itemId: image.itemId.value
        })
      );
    }

    imageMap.set(image.itemId.value, image.src);
  }

  return ok(imageMap);
}

function prepareRenderSections(
  sectionsInput: readonly RenderableSectionInput[],
  imageMap: ReadonlyMap<string, JekyllAssetUrlExpression>
): Result<readonly RenderGridSection[], GridgenError> {
  const sections: RenderGridSection[] = [];

  for (const sectionInput of sectionsInput) {
    const section = prepareRenderSection(sectionInput, imageMap);

    if (!section.ok) {
      return section;
    }

    sections.push(section.value);
  }

  return ok(sections);
}

function prepareRenderSection(
  section: RenderableSectionInput,
  imageMap: ReadonlyMap<string, JekyllAssetUrlExpression>
): Result<RenderGridSection, GridgenError> {
  const items = prepareRenderItems(section.items, imageMap);

  if (!items.ok) {
    return items;
  }

  return ok({
    id: section.id,
    items: items.value,
    name: section.name
  });
}

function prepareRenderItems(
  itemsInput: readonly RenderableItemInput[],
  imageMap: ReadonlyMap<string, JekyllAssetUrlExpression>
): Result<readonly RenderGridItem[], GridgenError> {
  const items: RenderGridItem[] = [];

  for (const itemInput of itemsInput) {
    const item = prepareRenderItem(itemInput, imageMap);

    if (!item.ok) {
      return item;
    }

    items.push(item.value);
  }

  return ok(items);
}

function prepareRenderItem(
  item: RenderableItemInput,
  imageMap: ReadonlyMap<string, JekyllAssetUrlExpression>
): Result<RenderGridItem, GridgenError> {
  const imageSource = item.image === undefined ? undefined : imageMap.get(item.id.value);

  if (item.image !== undefined && imageSource === undefined) {
    return err(
      createRenderError(
        GridgenErrorCode.RenderNotRenderable,
        "Missing generated image URL for renderable item.",
        {
          itemId: item.id.value
        }
      )
    );
  }

  return ok({
    ...(item.description === undefined ? {} : { description: item.description }),
    ...(imageSource === undefined || item.image === undefined
      ? {}
      : {
          image: {
            alt: resolveImageAltText(item.title, item.image.alt),
            src: imageSource
          }
        }),
    ...(item.link === undefined ? {} : { link: item.link }),
    ...(item.title === undefined ? {} : { title: item.title }),
    id: item.id
  });
}

/**
 * Renders static Jekyll include HTML for one prepared collection.
 *
 * @param input Prepared render model.
 * @returns Static HTML include contents.
 */
export function renderGridHtml(input: RenderGridInput): string {
  const collectionHeadingId = `gridgen-${input.collectionId.value}-title`;
  const sectionsHtml = input.sections
    .map((section) => renderSection(input.collectionId, section))
    .join("");

  return [
    generatedFileComment,
    `<link rel="stylesheet" href="${escapeHtmlAttribute(input.stylesheetHref.value)}">`,
    `<section class="gridgen-collection gridgen-collection--${input.layout}" aria-labelledby="${escapeHtmlAttribute(collectionHeadingId)}">`,
    `<header class="gridgen-header"><h1 class="gridgen-title" id="${escapeHtmlAttribute(collectionHeadingId)}">${escapeHtmlText(input.title.value)}</h1></header>`,
    sectionsHtml,
    "</section>"
  ].join("");
}

/**
 * Renders generated collection data JSON for framework component targets.
 *
 * @param input Prepared render model.
 * @returns Stable JSON string.
 */
export function renderGridDataJson(input: RenderGridInput): string {
  return `${JSON.stringify(serializeRenderedGridCollection(input), undefined, 2)}\n`;
}

/**
 * Renders the reusable Astro React component source.
 *
 * @returns TypeScript React component source.
 */
export function renderAstroReactComponent(): string {
  return `/* Generated by gridgen. Do not edit by hand. */
import type { ReactElement } from "react";

export type GridgenLayout = "classic" | "poster";

export interface GridgenRenderedImage {
  readonly alt: string;
  readonly src: string;
}

export interface GridgenRenderedItem {
  readonly description?: string;
  readonly id: string;
  readonly image?: GridgenRenderedImage;
  readonly link?: string;
  readonly title?: string;
}

export interface GridgenRenderedSection {
  readonly id: string;
  readonly items: readonly GridgenRenderedItem[];
  readonly name: string;
}

export interface GridgenRenderedCollection {
  readonly id: string;
  readonly layout: GridgenLayout;
  readonly renderDataVersion: 1;
  readonly sections: readonly GridgenRenderedSection[];
  readonly title: string;
}

export interface GridgenRecommendationGridProps {
  readonly collection: GridgenRenderedCollection;
}

export function GridgenRecommendationGrid({
  collection
}: GridgenRecommendationGridProps): ReactElement {
  const titleId = \`gridgen-\${collection.id}-title\`;

  return (
    <section
      aria-labelledby={titleId}
      className={\`gridgen-collection gridgen-collection--\${collection.layout}\`}
    >
      <header className="gridgen-header">
        <h1 className="gridgen-title" id={titleId}>
          {collection.title}
        </h1>
      </header>
      {collection.sections.map((section) => (
        <GridgenSection collectionId={collection.id} key={section.id} section={section} />
      ))}
    </section>
  );
}

export default GridgenRecommendationGrid;

function GridgenSection({
  collectionId,
  section
}: {
  readonly collectionId: string;
  readonly section: GridgenRenderedSection;
}): ReactElement {
  const sectionId = \`gridgen-\${collectionId}-\${section.id}\`;

  return (
    <section aria-labelledby={sectionId} className="gridgen-section">
      <h2 className="gridgen-section-title" id={sectionId}>
        {section.name}
      </h2>
      <div className="gridgen-grid">
        {section.items.map((item) => (
          <GridgenItem item={item} key={item.id} />
        ))}
      </div>
    </section>
  );
}

function GridgenItem({ item }: { readonly item: GridgenRenderedItem }): ReactElement {
  const contents = (
    <>
      {item.image === undefined ? undefined : (
        <img alt={item.image.alt} className="gridgen-item-image" src={item.image.src} />
      )}
      {item.title === undefined && item.description === undefined ? undefined : (
        <div className="gridgen-item-body">
          {item.title === undefined ? undefined : (
            <h4 className="gridgen-item-title">{item.title}</h4>
          )}
          {item.description === undefined ? undefined : (
            <p className="gridgen-item-description">{item.description}</p>
          )}
        </div>
      )}
    </>
  );

  return (
    <article className="gridgen-item">
      {item.link === undefined ? (
        <div className="gridgen-item-link">{contents}</div>
      ) : (
        <a className="gridgen-item-link" href={item.link}>
          {contents}
        </a>
      )}
    </article>
  );
}
`;
}

/**
 * Renders the shared Gridgen stylesheet.
 *
 * @returns Static CSS content.
 */
export function renderGridCss(): string {
  return `${generatedFileComment}
.gridgen-collection {
  color: inherit;
  display: grid;
  gap: 2rem;
}

.gridgen-header {
  border-bottom: 1px solid color-mix(in srgb, currentColor 18%, transparent);
  padding-bottom: 0.75rem;
}

.gridgen-title,
.gridgen-section-title,
.gridgen-item-title {
  letter-spacing: 0;
  margin: 0;
}

.gridgen-section {
  display: grid;
  gap: 1rem;
}

.gridgen-section-title {
  font-size: 1rem;
  font-weight: 700;
}

.gridgen-grid {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fill, minmax(12rem, 1fr));
}

.gridgen-item {
  display: grid;
  gap: 0.75rem;
}

.gridgen-item-link {
  color: inherit;
  display: grid;
  gap: 0.75rem;
  text-decoration: none;
}

.gridgen-item-image {
  aspect-ratio: 1 / 1;
  border-radius: 0.5rem;
  display: block;
  height: auto;
  object-fit: cover;
  width: 100%;
}

.gridgen-item-body {
  display: grid;
  gap: 0.35rem;
}

.gridgen-item-title {
  font-size: 0.95rem;
  font-weight: 700;
}

.gridgen-item-description {
  font-size: 0.875rem;
  line-height: 1.5;
  margin: 0;
  opacity: 0.82;
}

.gridgen-collection--poster {
  --gridgen-poster-tile-size: clamp(7.5rem, 18vw, 11rem);
  background: transparent;
  color: inherit;
  gap: clamp(2.5rem, 5vw, 4.5rem);
  margin-inline: auto;
  max-width: 92rem;
  padding: clamp(1.5rem, 4vw, 3.25rem);
}

.gridgen-collection--poster .gridgen-header {
  border-bottom: 0;
  padding-bottom: clamp(0.75rem, 2vw, 1.75rem);
  text-align: center;
}

.gridgen-collection--poster .gridgen-title {
  font-size: clamp(3rem, 10vw, 7.5rem);
  font-weight: 900;
  line-height: 1;
  max-width: 100%;
  overflow-wrap: anywhere;
  text-transform: uppercase;
}

.gridgen-collection--poster .gridgen-section {
  gap: clamp(1.75rem, 4vw, 4rem);
  padding-top: clamp(0.5rem, 1.5vw, 1.5rem);
}

.gridgen-collection--poster .gridgen-section-title {
  font-size: clamp(1.15rem, 2.4vw, 1.8rem);
  font-weight: 900;
  line-height: 1;
  text-align: left;
  text-transform: uppercase;
}

.gridgen-collection--poster .gridgen-grid {
  align-items: start;
  gap: clamp(2.5rem, 5vw, 4.25rem) clamp(1.5rem, 3vw, 2.25rem);
  grid-template-columns: repeat(auto-fit, minmax(0, var(--gridgen-poster-tile-size)));
  justify-content: start;
}

.gridgen-collection--poster .gridgen-item,
.gridgen-collection--poster .gridgen-item-link {
  gap: 0;
  min-width: 0;
  width: var(--gridgen-poster-tile-size);
}

.gridgen-collection--poster .gridgen-item-image {
  border-radius: 0;
}

.gridgen-collection--poster .gridgen-item-body {
  gap: 0.2rem;
  text-align: center;
}

.gridgen-collection--poster .gridgen-item-title {
  font-size: 0.875rem;
  font-style: normal;
  font-weight: 500;
  line-height: 1.15;
}

.gridgen-collection--poster .gridgen-item-description {
  font-size: 0.82rem;
  line-height: 1.15;
  opacity: 0.88;
}

`;
}

function serializeRenderedGridCollection(input: RenderGridInput): RenderedGridCollectionJson {
  return {
    id: input.collectionId.value,
    layout: input.layout,
    renderDataVersion: 1,
    sections: input.sections.map((section) => ({
      id: section.id.value,
      items: section.items.map(serializeRenderedGridItem),
      name: section.name.value
    })),
    title: input.title.value
  };
}

function serializeRenderedGridItem(item: RenderGridItem): RenderedGridItemJson {
  return {
    ...(item.description === undefined ? {} : { description: item.description.value }),
    ...(item.image === undefined
      ? {}
      : {
          image: {
            alt: item.image.alt,
            src: item.image.src.value
          }
        }),
    ...(item.link === undefined ? {} : { link: serializeGridLink(item.link) }),
    ...(item.title === undefined ? {} : { title: item.title.value }),
    id: item.id.value
  };
}

function serializeGridLink(link: GridLink): string {
  switch (link.type) {
    case "absolute":
      return link.href;
    case "site":
      return link.href.value;
  }
}

function renderSection(collectionId: CollectionId, section: RenderGridSection): string {
  const sectionHeadingId = `gridgen-${collectionId.value}-${section.id.value}`;
  const itemsHtml = section.items.map(renderItem).join("");
  const headingHtml = `<h2 class="gridgen-section-title" id="${escapeHtmlAttribute(sectionHeadingId)}">${escapeHtmlText(section.name.value)}</h2>`;

  return `<section class="gridgen-section" aria-labelledby="${escapeHtmlAttribute(sectionHeadingId)}">${headingHtml}<div class="gridgen-grid">${itemsHtml}</div></section>`;
}

function renderItem(item: RenderGridItem): string {
  const imageHtml =
    item.image === undefined
      ? ""
      : `<img class="gridgen-item-image" src="${escapeHtmlAttribute(item.image.src.value)}" alt="${escapeHtmlAttribute(item.image.alt)}">`;
  const titleHtml =
    item.title === undefined
      ? ""
      : `<h4 class="gridgen-item-title">${escapeHtmlText(item.title.value)}</h4>`;
  const descriptionHtml =
    item.description === undefined
      ? ""
      : `<p class="gridgen-item-description">${escapeHtmlText(item.description.value)}</p>`;
  const bodyHtml =
    titleHtml.length === 0 && descriptionHtml.length === 0
      ? ""
      : `<div class="gridgen-item-body">${titleHtml}${descriptionHtml}</div>`;
  const contentsHtml = `${imageHtml}${bodyHtml}`;

  if (item.link === undefined) {
    return `<article class="gridgen-item"><div class="gridgen-item-link">${contentsHtml}</div></article>`;
  }

  return `<article class="gridgen-item"><a class="gridgen-item-link" href="${escapeHtmlAttribute(renderLinkHref(item.link))}">${contentsHtml}</a></article>`;
}

function renderLinkHref(link: GridLink): string {
  return link.type === "absolute" ? link.href : link.href.value;
}

function resolveImageAltText(
  title: NonEmptyText | undefined,
  explicitAltText: string | undefined
): string {
  if (explicitAltText === undefined) {
    return title?.value ?? "";
  }

  const trimmedAltText = explicitAltText.trim();

  return trimmedAltText.length === 0 ? (title?.value ?? "") : trimmedAltText;
}

function escapeHtmlText(input: string): string {
  return input.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function escapeHtmlAttribute(input: string): string {
  return escapeHtmlText(input).replaceAll('"', "&quot;");
}
