import type {
  CollectionId,
  GridLink,
  ItemId,
  NonEmptyText,
  RenderableCollection,
  SafeLocalLink,
  SectionId
} from "../collection/types";
import { createRenderError, type GridgenError, GridgenErrorCode } from "../errors/errors";
import { err, ok, type Result } from "../result/result";

const generatedFileComment = "<!-- Generated by gridgen. Do not edit by hand. -->";
const stylesheetUrlPrefix = "{{ '";
const stylesheetUrlSuffix = "' | relative_url }}";

/**
 * Liquid-safe local asset URL expression used in generated HTML.
 *
 * @property value Liquid expression string.
 */
export interface JekyllAssetUrlExpression {
  readonly value: string;
}

/**
 * Prepared image reference ready for HTML rendering.
 *
 * @property alt Resolved alt text.
 * @property src Generated local image source.
 */
export interface RenderGridImage {
  readonly alt: string;
  readonly src: JekyllAssetUrlExpression;
}

/**
 * Prepared recommendation item ready for HTML rendering.
 *
 * @property description Optional non-empty description.
 * @property id Stable item ID.
 * @property image Prepared generated image.
 * @property link Renderable item link.
 * @property title Non-empty title.
 */
export interface RenderGridItem {
  readonly description?: NonEmptyText;
  readonly id: ItemId;
  readonly image: RenderGridImage;
  readonly link: GridLink;
  readonly title: NonEmptyText;
}

/**
 * Prepared recommendation section ready for HTML rendering.
 *
 * @property id Stable section ID.
 * @property items Ordered prepared items.
 * @property name Non-empty section title.
 */
export interface RenderGridSection {
  readonly id: SectionId;
  readonly items: readonly RenderGridItem[];
  readonly name: NonEmptyText;
}

/**
 * Prepared render input with all asset URLs already resolved.
 *
 * @property collectionId Stable collection ID.
 * @property sections Ordered prepared sections.
 * @property stylesheetHref Shared stylesheet liquid expression.
 * @property title Non-empty collection title.
 */
export interface RenderGridInput {
  readonly collectionId: CollectionId;
  readonly sections: readonly RenderGridSection[];
  readonly stylesheetHref: JekyllAssetUrlExpression;
  readonly title: NonEmptyText;
}

/**
 * Prepared item image mapping used to build renderer input.
 *
 * @property itemId Stable item ID.
 * @property src Generated local image URL expression.
 */
export interface PreparedRenderImage {
  readonly itemId: ItemId;
  readonly src: JekyllAssetUrlExpression;
}

/**
 * Input used to prepare a render-ready collection from a renderable collection.
 *
 * @property collection Renderable source collection.
 * @property images Generated image URLs keyed by item ID.
 * @property stylesheetHref Shared stylesheet liquid expression.
 */
export interface PrepareRenderGridInput {
  readonly collection: RenderableCollection;
  readonly images: readonly PreparedRenderImage[];
  readonly stylesheetHref: JekyllAssetUrlExpression;
}

/**
 * Converts a safe root-relative asset path into a Jekyll `relative_url` expression.
 *
 * @param href Safe local asset path.
 * @returns Liquid expression string for generated HTML attributes.
 */
export function createJekyllAssetUrlExpression(href: SafeLocalLink): JekyllAssetUrlExpression {
  return {
    value: `${stylesheetUrlPrefix}${href.value}${stylesheetUrlSuffix}`
  };
}

/**
 * Prepares one renderable collection for the HTML renderer.
 *
 * @param input Render preparation input.
 * @returns Prepared render model or a structured failure when an item image URL is missing.
 */
export function prepareRenderGrid(
  input: PrepareRenderGridInput
): Result<RenderGridInput, GridgenError> {
  const imageMap = new Map<string, JekyllAssetUrlExpression>();

  for (const image of input.images) {
    if (imageMap.has(image.itemId.value)) {
      return err(
        createRenderError(GridgenErrorCode.RenderNotRenderable, "Duplicate generated image URL.", {
          itemId: image.itemId.value
        })
      );
    }

    imageMap.set(image.itemId.value, image.src);
  }

  const sections: RenderGridSection[] = [];

  for (const section of input.collection.sections) {
    const items: RenderGridItem[] = [];

    for (const item of section.items) {
      const imageSource = imageMap.get(item.id.value);

      if (imageSource === undefined) {
        return err(
          createRenderError(
            GridgenErrorCode.RenderNotRenderable,
            "Missing generated image URL for renderable item.",
            {
              itemId: item.id.value
            }
          )
        );
      }

      items.push({
        ...(item.description === undefined ? {} : { description: item.description }),
        id: item.id,
        image: {
          alt: resolveImageAltText(item.title, item.image.alt),
          src: imageSource
        },
        link: item.link,
        title: item.title
      });
    }

    sections.push({
      id: section.id,
      items,
      name: section.name
    });
  }

  return ok({
    collectionId: input.collection.id,
    sections,
    stylesheetHref: input.stylesheetHref,
    title: input.collection.title
  });
}

/**
 * Renders static Jekyll include HTML for one prepared collection.
 *
 * @param input Prepared render model.
 * @returns Static HTML include contents.
 */
export function renderGridHtml(input: RenderGridInput): string {
  const collectionHeadingId = `gridgen-${input.collectionId.value}-title`;
  const sectionsHtml = input.sections
    .map((section) => renderSection(input.collectionId, section))
    .join("");

  return [
    generatedFileComment,
    `<link rel="stylesheet" href="${escapeHtmlAttribute(input.stylesheetHref.value)}">`,
    `<section class="gridgen-collection" aria-labelledby="${escapeHtmlAttribute(collectionHeadingId)}">`,
    `<header class="gridgen-header"><h2 class="gridgen-title" id="${escapeHtmlAttribute(collectionHeadingId)}">${escapeHtmlText(input.title.value)}</h2></header>`,
    sectionsHtml,
    "</section>"
  ].join("");
}

/**
 * Renders the shared Gridgen stylesheet.
 *
 * @returns Static CSS content.
 */
export function renderGridCss(): string {
  return `${generatedFileComment}
.gridgen-collection {
  color: inherit;
  display: grid;
  gap: 2rem;
}

.gridgen-header {
  border-bottom: 1px solid color-mix(in srgb, currentColor 18%, transparent);
  padding-bottom: 0.75rem;
}

.gridgen-title,
.gridgen-section-title,
.gridgen-item-title {
  letter-spacing: 0;
  margin: 0;
}

.gridgen-section {
  display: grid;
  gap: 1rem;
}

.gridgen-section-title {
  font-size: 1rem;
  font-weight: 700;
}

.gridgen-grid {
  display: grid;
  gap: 1rem;
  grid-template-columns: repeat(auto-fill, minmax(12rem, 1fr));
}

.gridgen-item {
  display: grid;
  gap: 0.75rem;
}

.gridgen-item-link {
  color: inherit;
  display: grid;
  gap: 0.75rem;
  text-decoration: none;
}

.gridgen-item-image {
  aspect-ratio: 1 / 1;
  border-radius: 0.5rem;
  display: block;
  height: auto;
  object-fit: cover;
  width: 100%;
}

.gridgen-item-body {
  display: grid;
  gap: 0.35rem;
}

.gridgen-item-title {
  font-size: 0.95rem;
  font-weight: 700;
}

.gridgen-item-description {
  font-size: 0.875rem;
  line-height: 1.5;
  margin: 0;
  opacity: 0.82;
}`;
}

function renderSection(collectionId: CollectionId, section: RenderGridSection): string {
  const sectionHeadingId = `gridgen-${collectionId.value}-${section.id.value}`;
  const itemsHtml = section.items.map(renderItem).join("");

  return `<section class="gridgen-section" aria-labelledby="${escapeHtmlAttribute(sectionHeadingId)}"><h3 class="gridgen-section-title" id="${escapeHtmlAttribute(sectionHeadingId)}">${escapeHtmlText(section.name.value)}</h3><div class="gridgen-grid">${itemsHtml}</div></section>`;
}

function renderItem(item: RenderGridItem): string {
  const descriptionHtml =
    item.description === undefined
      ? ""
      : `<p class="gridgen-item-description">${escapeHtmlText(item.description.value)}</p>`;

  return `<article class="gridgen-item"><a class="gridgen-item-link" href="${escapeHtmlAttribute(renderLinkHref(item.link))}"><img class="gridgen-item-image" src="${escapeHtmlAttribute(item.image.src.value)}" alt="${escapeHtmlAttribute(item.image.alt)}"><div class="gridgen-item-body"><h4 class="gridgen-item-title">${escapeHtmlText(item.title.value)}</h4>${descriptionHtml}</div></a></article>`;
}

function renderLinkHref(link: GridLink): string {
  return link.type === "absolute" ? link.href : link.href.value;
}

function resolveImageAltText(title: NonEmptyText, explicitAltText: string | undefined): string {
  if (explicitAltText === undefined) {
    return title.value;
  }

  const trimmedAltText = explicitAltText.trim();

  return trimmedAltText.length === 0 ? title.value : trimmedAltText;
}

function escapeHtmlText(input: string): string {
  return input.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

function escapeHtmlAttribute(input: string): string {
  return escapeHtmlText(input).replaceAll('"', "&quot;");
}
