import * as path from "node:path";

import {
  type GridgenError,
  GridgenErrorCode,
  parseRenderableCollection,
  planAstroReactBuild,
  planJekyllBuild,
  type RenderableCollection,
  type Result
} from "@gridgen/core";
import { describe, expect, it } from "bun:test";

describe("build planner", () => {
  it("plans deterministic include, stylesheet, image, and cleanup outputs", () => {
    const collection = createRenderableCollection();
    const jekyllRoot = path.join(path.sep, "tmp", "jekyll-site");
    const firstPlan = unwrapOk(
      planJekyllBuild({
        collection,
        jekyllRoot
      })
    );
    const secondPlan = unwrapOk(
      planJekyllBuild({
        collection,
        jekyllRoot
      })
    );

    expect(firstPlan).toEqual(secondPlan);
    expect(firstPlan.htmlOutput.outputPath.relativePath.value).toBe("_includes/gridgen/music.html");
    expect(firstPlan.cssOutput.outputPath.relativePath.value).toBe("assets/gridgen/gridgen.css");
    expect(firstPlan.cleanupDirectory.relativePath.value).toBe("assets/gridgen/music");
    expect(
      firstPlan.imageOutputs.map((imageOutput) => imageOutput.outputPath.relativePath.value)
    ).toEqual(["assets/gridgen/music/album-a.webp", "assets/gridgen/music/album-b.webp"]);
    expect(firstPlan.imageOutputs.map((imageOutput) => imageOutput.sourceFileName.value)).toEqual([
      "album-a.png",
      "album-b.png"
    ]);
    expect(firstPlan.htmlOutput.contents).toContain(
      "{{ '/assets/gridgen/music/album-a.webp' | relative_url }}"
    );
    expect(firstPlan.htmlOutput.contents).toContain('alt="Album A cover"');
    expect(firstPlan.cssOutput.contents).toContain("Generated by gridgen");
  });

  it("fails before any write when the Jekyll root is unsafe", () => {
    const result = planJekyllBuild({
      collection: createRenderableCollection(),
      jekyllRoot: "./jekyll-site"
    });

    expect(unwrapErr(result).code).toBe(GridgenErrorCode.PathUnsafe);
  });

  it("does not plan image outputs for items without images", () => {
    const collection = unwrapOk(
      parseRenderableCollection({
        id: "music",
        schemaVersion: 1,
        sections: [
          {
            id: "s-tier",
            items: [
              {
                id: "blank-item"
              }
            ],
            name: "S Tier"
          }
        ],
        title: "Music"
      })
    );
    const plan = unwrapOk(
      planJekyllBuild({
        collection,
        jekyllRoot: path.join(path.sep, "tmp", "jekyll-site")
      })
    );

    expect(plan.imageOutputs).toEqual([]);
    expect(plan.htmlOutput.contents).not.toContain("gridgen-item-image");
    expect(plan.htmlOutput.contents).not.toContain("/assets/gridgen/music/blank-item.webp");
  });

  it("plans poster layout output without changing image asset planning", () => {
    const collection = createRenderableCollection();
    const plan = unwrapOk(
      planJekyllBuild({
        collection,
        jekyllRoot: path.join(path.sep, "tmp", "jekyll-site"),
        layout: "poster"
      })
    );

    expect(plan.htmlOutput.contents).toContain("gridgen-collection--poster");
    expect(plan.htmlOutput.contents).toContain(
      '<h2 class="gridgen-section-title" id="gridgen-music-s-tier">S Tier</h2>'
    );
    expect(
      plan.imageOutputs.map((imageOutput) => imageOutput.outputPath.relativePath.value)
    ).toEqual(["assets/gridgen/music/album-a.webp", "assets/gridgen/music/album-b.webp"]);
  });

  it("plans Astro React component, stylesheet, render data, images, and public URLs", () => {
    const collection = createRenderableCollection();
    const astroRoot = path.join(path.sep, "tmp", "astro-site");
    const plan = unwrapOk(
      planAstroReactBuild({
        astroRoot,
        collection
      })
    );

    expect(plan.componentOutput.outputPath.relativePath.value).toBe(
      "src/gridgen/GridgenRecommendationGrid.tsx"
    );
    expect(plan.cssOutput.outputPath.relativePath.value).toBe("src/gridgen/gridgen.css");
    expect(plan.dataOutput.outputPath.relativePath.value).toBe("src/gridgen/music.json");
    expect(plan.cleanupDirectory.relativePath.value).toBe("public/gridgen/assets/music");
    expect(
      plan.imageOutputs.map((imageOutput) => imageOutput.outputPath.relativePath.value)
    ).toEqual([
      "public/gridgen/assets/music/album-a.webp",
      "public/gridgen/assets/music/album-b.webp"
    ]);
    expect(plan.dataOutput.contents).toContain('"renderDataVersion": 1');
    expect(plan.dataOutput.contents).toContain('"layout": "poster"');
    expect(plan.dataOutput.contents).toContain('"/gridgen/assets/music/album-a.webp"');
    expect(plan.dataOutput.contents).not.toContain("sourceFileName");
    expect(plan.dataOutput.contents).not.toContain('"crop"');
    expect(plan.componentOutput.contents).toContain("export default GridgenRecommendationGrid;");
    expect(plan.componentOutput.contents).not.toContain('import "./gridgen.css"');
  });

  it("plans explicit Astro React classic layout render data", () => {
    const plan = unwrapOk(
      planAstroReactBuild({
        astroRoot: path.join(path.sep, "tmp", "astro-site"),
        collection: createRenderableCollection(),
        layout: "classic"
      })
    );

    expect(plan.dataOutput.contents).toContain('"layout": "classic"');
  });

  it("fails before any write when the Astro root is unsafe", () => {
    const result = planAstroReactBuild({
      astroRoot: "./astro-site",
      collection: createRenderableCollection()
    });

    expect(unwrapErr(result).code).toBe(GridgenErrorCode.PathUnsafe);
  });
});

function createRenderableCollection(): RenderableCollection {
  return unwrapOk(
    parseRenderableCollection({
      id: "music",
      schemaVersion: 1,
      sections: [
        {
          id: "s-tier",
          items: [
            {
              id: "album-a",
              image: {
                alt: "Album A cover",
                crop: {
                  height: 100,
                  unit: "percent",
                  width: 100,
                  x: 0,
                  y: 0
                },
                sourceFileName: "album-a.png",
                type: "file"
              },
              link: "https://example.com/a",
              title: "Album A"
            }
          ],
          name: "S Tier"
        },
        {
          id: "a-tier",
          items: [
            {
              id: "album-b",
              image: {
                crop: {
                  height: 100,
                  unit: "percent",
                  width: 100,
                  x: 0,
                  y: 0
                },
                sourceFileName: "album-b.png",
                type: "file"
              },
              link: "/albums/b/",
              title: "Album B"
            }
          ],
          name: "A Tier"
        }
      ],
      title: "Music"
    })
  );
}

function unwrapOk<Value, Failure>(result: Result<Value, Failure>): Value {
  if (!result.ok) {
    throw new Error("Expected an ok result.");
  }

  return result.value;
}

function unwrapErr<Value>(result: Result<Value, GridgenError>): GridgenError {
  if (result.ok) {
    throw new Error("Expected an error result.");
  }

  return result.error;
}
