import {
  createJekyllAssetUrlExpression,
  type GridgenError,
  GridgenErrorCode,
  type JekyllAssetUrlExpression,
  parseRenderableCollection,
  parseSafeLocalLink,
  prepareRenderGrid,
  type RenderableCollection,
  renderGridCss,
  renderGridHtml,
  type Result
} from "@gridgen/core";
import { describe, expect, it } from "bun:test";

describe("grid renderer", () => {
  it("renders escaped static HTML with saved order, generated asset URLs, and alt fallback", () => {
    const collection = createRenderableCollection();
    const albumA = getRenderableItem(collection, 0, 0);
    const albumB = getRenderableItem(collection, 1, 0);
    const stylesheetHref = createAssetExpression("/assets/gridgen/gridgen.css");
    const prepared = unwrapOk(
      prepareRenderGrid({
        collection,
        images: [
          {
            itemId: albumA.id,
            src: createAssetExpression("/assets/gridgen/music/album-a.webp")
          },
          {
            itemId: albumB.id,
            src: createAssetExpression("/assets/gridgen/music/album-b.webp")
          }
        ],
        stylesheetHref
      })
    );
    const html = renderGridHtml(prepared);

    expect(html).toContain("<!-- Generated by gridgen. Do not edit by hand. -->");
    expect(html).toContain(`href="${stylesheetHref.value}"`);
    expect(html).toContain(
      '<h1 class="gridgen-title" id="gridgen-music-title">Music &amp; More</h1>'
    );
    expect(html).toContain("S Tier");
    expect(html).toContain("A Tier");
    expect(html).toContain("Album &lt;A&gt;");
    expect(html).toContain("Best &amp; loudest");
    expect(html).toContain(
      `src="${createAssetExpression("/assets/gridgen/music/album-a.webp").value}"`
    );
    expect(html).toContain('alt="Album &lt;A&gt;"');
    expect(html).toContain('alt="Album B cover"');
    expect(html).not.toContain("<script");
    expect(html.indexOf("S Tier")).toBeLessThan(html.indexOf("A Tier"));
    expect(html.indexOf("Album &lt;A&gt;")).toBeLessThan(html.indexOf("Album B"));
  });

  it("rejects prepared render input when an item image URL is missing", () => {
    const collection = createRenderableCollection();
    const albumA = getRenderableItem(collection, 0, 0);
    const result = prepareRenderGrid({
      collection,
      images: [
        {
          itemId: albumA.id,
          src: createAssetExpression("/assets/gridgen/music/album-a.webp")
        }
      ],
      stylesheetHref: createAssetExpression("/assets/gridgen/gridgen.css")
    });

    expect(unwrapErr(result).code).toBe(GridgenErrorCode.RenderNotRenderable);
  });

  it("rejects duplicate generated image URLs for the same item", () => {
    const collection = createRenderableCollection();
    const albumA = getRenderableItem(collection, 0, 0);
    const result = prepareRenderGrid({
      collection,
      images: [
        {
          itemId: albumA.id,
          src: createAssetExpression("/assets/gridgen/music/album-a.webp")
        },
        {
          itemId: albumA.id,
          src: createAssetExpression("/assets/gridgen/music/album-a-duplicate.webp")
        },
        {
          itemId: getRenderableItem(collection, 1, 0).id,
          src: createAssetExpression("/assets/gridgen/music/album-b.webp")
        }
      ],
      stylesheetHref: createAssetExpression("/assets/gridgen/gridgen.css")
    });

    expect(unwrapErr(result).code).toBe(GridgenErrorCode.RenderNotRenderable);
  });

  it("renders items without authored title, link, image, or description", () => {
    const collection = unwrapOk(
      parseRenderableCollection({
        id: "music",
        schemaVersion: 1,
        sections: [
          {
            id: "s-tier",
            items: [
              {
                id: "blank-item"
              }
            ],
            name: "S Tier"
          }
        ],
        title: "Music"
      })
    );
    const prepared = unwrapOk(
      prepareRenderGrid({
        collection,
        images: [],
        stylesheetHref: createAssetExpression("/assets/gridgen/gridgen.css")
      })
    );
    const html = renderGridHtml(prepared);

    expect(prepared.sections[0]?.items[0]).toEqual({ id: { value: "blank-item" } });
    expect(html).toContain('<article class="gridgen-item"><div class="gridgen-item-link">');
    expect(html).not.toContain("<img");
    expect(html).not.toContain("<h4");
    expect(html).not.toContain('<a class="gridgen-item-link"');
  });

  it("renders poster layout with visible tier labels and transparent generated output", () => {
    const collection = createRenderableCollection();
    const albumA = getRenderableItem(collection, 0, 0);
    const albumB = getRenderableItem(collection, 1, 0);
    const prepared = unwrapOk(
      prepareRenderGrid({
        collection,
        images: [
          {
            itemId: albumA.id,
            src: createAssetExpression("/assets/gridgen/music/album-a.webp")
          },
          {
            itemId: albumB.id,
            src: createAssetExpression("/assets/gridgen/music/album-b.webp")
          }
        ],
        layout: "poster",
        stylesheetHref: createAssetExpression("/assets/gridgen/gridgen.css")
      })
    );
    const html = renderGridHtml(prepared);
    const css = renderGridCss();

    expect(prepared.layout).toBe("poster");
    expect(html).toContain("gridgen-collection--poster");
    expect(html).toContain(
      '<h2 class="gridgen-section-title" id="gridgen-music-s-tier">S Tier</h2>'
    );
    expect(html).toContain(
      '<h2 class="gridgen-section-title" id="gridgen-music-a-tier">A Tier</h2>'
    );
    expect(html).toContain("Album &lt;A&gt;");
    expect(html).toContain("Best &amp; loudest");
    expect(html).toContain('href="https://example.com/a"');
    expect(css).toContain(".gridgen-collection--poster");
    expect(css).toContain("background: transparent;");
    expect(css).toContain("--gridgen-poster-tile-size: clamp(7.5rem, 18vw, 11rem);");
    expect(css).toContain(
      "grid-template-columns: repeat(auto-fit, minmax(0, var(--gridgen-poster-tile-size)));"
    );
    expect(css).toContain("justify-content: start;");
    expect(css).toContain("width: var(--gridgen-poster-tile-size);");
    expect(css).toContain("font-style: normal;");
    expect(css).toContain("text-transform: uppercase;");
    expect(css).toContain("font-size: clamp(1.15rem, 2.4vw, 1.8rem);");
    expect(css).toContain("text-align: left;");
    expect(css).toContain("padding-bottom: clamp(0.75rem, 2vw, 1.75rem);");
    expect(css).toContain("padding-top: clamp(0.5rem, 1.5vw, 1.5rem);");
    expect(css).toContain("line-height: 1;");
    expect(css).toContain("overflow-wrap: anywhere;");
  });

  it("renders namespaced responsive CSS", () => {
    const css = renderGridCss();

    expect(css).toContain("Generated by gridgen");
    expect(css).toContain(".gridgen-collection");
    expect(css).toContain(".gridgen-grid");
    expect(css).toContain("grid-template-columns: repeat(auto-fill, minmax(12rem, 1fr));");
  });
});

function createRenderableCollection(): RenderableCollection {
  return unwrapOk(
    parseRenderableCollection({
      id: "music",
      schemaVersion: 1,
      sections: [
        {
          id: "s-tier",
          items: [
            {
              description: "Best & loudest",
              id: "album-a",
              image: {
                crop: {
                  height: 100,
                  unit: "percent",
                  width: 100,
                  x: 0,
                  y: 0
                },
                sourceFileName: "album-a.png",
                type: "file"
              },
              link: "https://example.com/a",
              title: "Album <A>"
            }
          ],
          name: "S Tier"
        },
        {
          id: "a-tier",
          items: [
            {
              id: "album-b",
              image: {
                alt: "Album B cover",
                crop: {
                  height: 100,
                  unit: "percent",
                  width: 100,
                  x: 0,
                  y: 0
                },
                sourceFileName: "album-b.png",
                type: "file"
              },
              link: "/albums/b/",
              title: "Album B"
            }
          ],
          name: "A Tier"
        }
      ],
      title: "Music & More"
    })
  );
}

function createAssetExpression(href: string): JekyllAssetUrlExpression {
  return createJekyllAssetUrlExpression(unwrapOk(parseSafeLocalLink(href)));
}

function getRenderableItem(
  collection: RenderableCollection,
  sectionIndex: number,
  itemIndex: number
): RenderableCollection["sections"][number]["items"][number] {
  const section = collection.sections[sectionIndex];

  if (section === undefined) {
    throw new Error("Expected renderable section.");
  }

  const item = section.items[itemIndex];

  if (item === undefined) {
    throw new Error("Expected renderable item.");
  }

  return item;
}

function unwrapOk<Value, Failure>(result: Result<Value, Failure>): Value {
  if (!result.ok) {
    throw new Error("Expected an ok result.");
  }

  return result.value;
}

function unwrapErr<Value>(result: Result<Value, GridgenError>): GridgenError {
  if (result.ok) {
    throw new Error("Expected an error result.");
  }

  return result.error;
}
