/* Generated by gridgen. Do not edit by hand. */
import type { ReactElement } from "react";

export type GridgenLayout = "classic" | "poster";

export interface GridgenRenderedImage {
  readonly alt: string;
  readonly src: string;
}

export interface GridgenRenderedItem {
  readonly description?: string;
  readonly id: string;
  readonly image?: GridgenRenderedImage;
  readonly link?: string;
  readonly title?: string;
}

export interface GridgenRenderedSection {
  readonly id: string;
  readonly items: readonly GridgenRenderedItem[];
  readonly name: string;
}

export interface GridgenRenderedCollection {
  readonly id: string;
  readonly layout: GridgenLayout;
  readonly renderDataVersion: 1;
  readonly sections: readonly GridgenRenderedSection[];
  readonly title: string;
}

export interface GridgenRecommendationGridProps {
  readonly collection: GridgenRenderedCollection;
}

export function GridgenRecommendationGrid({
  collection
}: GridgenRecommendationGridProps): ReactElement {
  const titleId = `gridgen-${collection.id}-title`;

  return (
    <section
      aria-labelledby={titleId}
      className={`gridgen-collection gridgen-collection--${collection.layout}`}
    >
      <header className="gridgen-header">
        <h1 className="gridgen-title" id={titleId}>
          {collection.title}
        </h1>
      </header>
      {collection.sections.map((section) => (
        <GridgenSection collectionId={collection.id} key={section.id} section={section} />
      ))}
    </section>
  );
}

export default GridgenRecommendationGrid;

function GridgenSection({
  collectionId,
  section
}: {
  readonly collectionId: string;
  readonly section: GridgenRenderedSection;
}): ReactElement {
  const sectionId = `gridgen-${collectionId}-${section.id}`;

  return (
    <section aria-labelledby={sectionId} className="gridgen-section">
      <h2 className="gridgen-section-title" id={sectionId}>
        {section.name}
      </h2>
      <div className="gridgen-grid">
        {section.items.map((item) => (
          <GridgenItem item={item} key={item.id} />
        ))}
      </div>
    </section>
  );
}

function GridgenItem({ item }: { readonly item: GridgenRenderedItem }): ReactElement {
  const contents = (
    <>
      {item.image === undefined ? undefined : (
        <img alt={item.image.alt} className="gridgen-item-image" src={item.image.src} />
      )}
      {item.title === undefined && item.description === undefined ? undefined : (
        <div className="gridgen-item-body">
          {item.title === undefined ? undefined : (
            <h4 className="gridgen-item-title">{item.title}</h4>
          )}
          {item.description === undefined ? undefined : (
            <p className="gridgen-item-description">{item.description}</p>
          )}
        </div>
      )}
    </>
  );

  return (
    <article className="gridgen-item">
      {item.link === undefined ? (
        <div className="gridgen-item-link">{contents}</div>
      ) : (
        <a className="gridgen-item-link" href={item.link}>
          {contents}
        </a>
      )}
    </article>
  );
}
